# Generated by Django 4.0.4 on 2022-05-22 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_archiveentry_staticpage_homepage_featured_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bottom_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.articlepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='left_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.articlepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.articlepage'),
        ),
    ]
