# Generated by Django 3.1.6 on 2021-09-14 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0004_auto_20210911_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
