# Generated by Django 4.0.4 on 2022-05-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0004_homepage_bottom_article_homepage_left_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo_invert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
