# Generated by Django 4.0.4 on 2022-05-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_logo_invert'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('staticpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.staticpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.staticpage',),
        ),
    ]
