# Generated by Django 3.1.6 on 2021-10-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211003_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
