# Generated by Django 4.0.4 on 2022-05-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamPage',
            new_name='About',
        ),
    ]
