# Generated by Django 4.0.4 on 2022-06-01 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0007_rename_teampage_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveentry',
            name='front_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='archiveentry',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='archiveentry',
            name='tags',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
