# Generated by Django 4.0.4 on 2022-06-03 01:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0008_archiveentry_front_image_archiveentry_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='lead_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='lede',
            field=models.CharField(default='lede', max_length=1024),
            preserve_default=False,
        ),
    ]
