# Generated by Django 3.1.6 on 2021-10-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211013_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='lede',
            field=models.CharField(default='Default lede', max_length=512),
            preserve_default=False,
        ),
    ]
