# Generated by Django 4.0.4 on 2022-06-03 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_staticpage_body_staticpage_lead_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='lede',
        ),
    ]
